### ISSUE TITLE
Error when running python scrape-st.py command

### ISSUE THREAD

**Issue by GRClark** [TekniskSupport/ST-zigbee-network-map#1]
Getting the following error and looking for guidance...

> /home/pi/.local/lib/python2.7/site-packages/bs4/element.py:16: UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.
>   'The soupsieve package is not installed. CSS selectors cannot be used.'
> Trying shard: https://graph-ap02-apnortheast2.api.smartthings.com
> Redirect deetected. Invalid login? Double check JSESSIONID
> Trying shard: https://graph-eu01-euwest1.api.smartthings.com
> Redirect deetected. Invalid login? Double check JSESSIONID
> Trying shard: https://graph-na04-useast2.api.smartthings.com
> Redirect deetected. Invalid login? Double check JSESSIONID
> Trying shard: https://graph-na02-useast1.api.smartthings.com
> Shard matching session found: https://graph-na02-useast1.api.smartthings.com
> Traceback (most recent call last):
>   File "scrape-st.py", line 1, in <module>
>     import _scrape
>   File "/home/pi/ST-zigbee-network-map-master/_scrape.py", line 37, in <module>
>     if (len(soup.select('#device-table > tbody > tr')) == 0):
>   File "/home/pi/.local/lib/python2.7/site-packages/bs4/element.py", line 1866, in select
>     "Cannot execute CSS selectors because the soupsieve package is not installed."
> NotImplementedError: Cannot execute CSS selectors because the soupsieve package is not installed.

But when I attempt to install the package that it says is not installed it gives me this message saying it's already installed...

> > pi@PECAN:~/ST-zigbee-network-map-master $ python -m pip install soupsieve
> Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
> Requirement already satisfied: soupsieve in /home/pi/.local/lib/python2.7/site-packages (1.9.6)
> Requirement already satisfied: backports.functools-lru-cache; python_version < "3" in /home/pi/.local/lib/python2.7/site-packages (from soupsieve) (1.6.4)

I have it working on Windows and looking to install on Raspberry Pi running Raspberry Pi OS (Raspbian)

**Comment by TekniskSupport** [comment]
Try using python3 instead

currently running a freshly installed computer with python 3.8.10, and it seemed to work as intended
